# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: write

    env:
      # 版本管理
      PROJECT_NAME: 'alinesno-infra-smart-brain-embedding-application'
      PRO_VERSION: '1.0.0-SNAPSHOT'
      CURRENT_PROFIRE: 'dev'
      BUILD_NUMBER: ${{ github.run_number }}

      # 容器镜像
      ALIYUN_CR_REGISTORY: 'registry.cn-shenzhen.aliyuncs.com'
      ALIYUN_CR_NAMESPACE: 'alinesno-infra-platform'

    steps:
      - uses: actions/checkout@v3

      - uses: aliyun/acr-login@v1
        with:
          region-id: 'cn-shenzhen' # example: cn-hangzhou
          access-key-id: '${{secrets.ALIYUN_CR_USERNAME}}'
          access-key-secret: '${{secrets.ALIYUN_CR_PASSWORD}}'

      - name: Deploy to AliyunCR
        run: |
          cd ${{ env.PROJECT_NAME }}
          docker build -t ${{ env.ALIYUN_CR_REGISTORY }}/${{ env.ALIYUN_CR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }} .
          docker push ${{ env.ALIYUN_CR_REGISTORY }}/${{ env.ALIYUN_CR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }}

      - uses: dbelyaev/action-checkstyle@v0.8.4
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.ALIYUN_CR_REGISTORY }}/${{ env.ALIYUN_CR_NAMESPACE }}/${{ env.PROJECT_NAME }}:${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: local remote scp
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_BATA_HOST_01 }}
          port: ${{ secrets.SERVER_BATA_PORT_01 }}
          user: ${{ secrets.SERVER_BATA_USER_01 }}
          pass: ${{ secrets.SERVER_BATA_KEY_01 }}
          local: "./deploy/*"
          remote: /home/github-action/${{ env.PROJECT_NAME }}

      - name: SSH Pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.SERVER_BATA_HOST_01 }}
          port: ${{ secrets.SERVER_BATA_PORT_01 }}
          user: ${{ secrets.SERVER_BATA_USER_01 }}
          pass: ${{ secrets.SERVER_BATA_KEY_01 }}
          connect_timeout: 30s
          script: |
            export PROJECT_NAME=${{ env.PROJECT_NAME }}
            export VERSION=${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }}

            export ALIYUN_CR_REGISTORY=${{ env.ALIYUN_CR_REGISTORY }}
            export ALIYUN_CR_NAMESPACE=${{ env.ALIYUN_CR_NAMESPACE }}
            export NAMESPACE=${{ secrets.K8S_NAMESPACE }}

            export CHATGPT_PROXY=${{ secrets.DEV_CHATGPT_PROXY }}
            export CHATGPT_SK=${{ secrets.DEV_CHATGPT_SK }}

            export INFRA_DEV_DOMAIN=${{ secrets.INFRA_BETA_SMART_DOMAIN }}

            envsubst < /home/github-action/${{ env.PROJECT_NAME }}/kubernetes-embedding-${{ env.CURRENT_PROFIRE }}.yml | kubectl apply -f -
