name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      # 版本管理
      PROJECT_NAME: 'alinesno-infra-smart-brain-admin'
      PRO_VERSION: '1.0.0-SNAPSHOT'
      CURRENT_PROFIRE: 'dev'
      BUILD_NUMBER: ${{ github.run_number }}

      # 容器镜像
      ALIYUN_CR_REGISTORY: 'registry.cn-shenzhen.aliyuncs.com'
      ALIYUN_CR_NAMESPACE: 'alinesno-infra-platform'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: |
          cd ${{ PROJECT_NAME }}
          npm install
          npm run build:prod

      - name: Build Docker image
        run: |
          cd ${{ PROJECT_NAME }}
          cp -r dist ./docker/
          docker build -t ${{ ALIYUN_CR_REGISTORY }}/${{ ALIYUN_CR_NAMESPACE }}/${{ PROJECT_NAME }}:${{ PRO_VERSION }}.${{ BUILD_NUMBER }} ./docker

      - name: local remote scp
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_BATA_HOST_01 }}
          port: ${{ secrets.SERVER_BATA_PORT_01 }}
          user: ${{ secrets.SERVER_BATA_USER_01 }}
          pass: ${{ secrets.SERVER_BATA_KEY_01 }}
          local: "./deploy/*"
          remote: /home/github-action/${{ PROJECT_NAME }}

      - name: SSH Pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.SERVER_BATA_HOST_01 }}
          port: ${{ secrets.SERVER_BATA_PORT_01 }}
          user: ${{ secrets.SERVER_BATA_USER_01 }}
          pass: ${{ secrets.SERVER_BATA_KEY_01 }}
          connect_timeout: 30s
          script: |
            export PROJECT_NAME=${{ env.PROJECT_NAME }}
            export VERSION=${{ env.PRO_VERSION }}.${{ env.BUILD_NUMBER }}

            export ALIYUN_CR_REGISTORY=${{ env.ALIYUN_CR_REGISTORY }}
            export ALIYUN_CR_NAMESPACE=${{ env.ALIYUN_CR_NAMESPACE }}
            export NAMESPACE=${{ secrets.K8S_NAMESPACE }}

            export INFRA_DEV_DOMAIN=${{ secrets.INFRA_BETA_SMART_DOMAIN }}

            envsubst < /home/github-action/${{ PROJECT_NAME }}/kubernetes-admin-${{ env.CURRENT_PROFIRE }}.yml | kubectl apply -f -
